---
language: cpp
dist: bionic

addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotoc-dev
      - libcgal-qt5-dev
      - libcppunit-dev
      - libjsoncpp-dev
      - ttf-dejavu

before_install:
  - sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json
  - sudo mkdir -p /usr/share/fonts/TTF
  - sudo ln -s /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf /usr/share/fonts/TTF/DejaVuSansMono.ttf

install:
  - ./install.sh

before_script:
  - cd bin
  - wget https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf

script:
  - ./pipeline.sh ../config/example.conf ./baden-wuerttemberg-latest.osm.pbf
